### ISSUE TITLE
StackOverflowError in OptimizedCompiler.encodePredicatedChoice()

### ISSUE THREAD

**Issue by imasahiro** [nez-peg/nez#46]
When nez compiling following peg code, StackOverflowError is thrown.

```
$ cat hoge.nez
File
    = { TERM #Tag }

TERM
    = 'A' (TERM / 'B') 'C'*

$ java -jar ../nez.jar compile -p hoge.nez
generating .. hoge.moz
Exception in thread "main" java.lang.StackOverflowError
    at nez.lang.expr.Psequence.toMultiCharSequence(Psequence.java:186)
    at nez.lang.expr.Psequence.encode(Psequence.java:170)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.OptimizedCompiler.encodePredicatedChoice(OptimizedCompiler.java:137)
    at nez.parser.OptimizedCompiler.encodePchoice(OptimizedCompiler.java:110)
    at nez.lang.expr.Pchoice.encode(Pchoice.java:111)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.PlainCompiler.encodePsequence(PlainCompiler.java:113)
    at nez.lang.expr.Psequence.encode(Psequence.java:175)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.PlainCompiler.encodePsequence(PlainCompiler.java:113)
    at nez.lang.expr.Psequence.encode(Psequence.java:175)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.OptimizedCompiler.encodePredicatedChoice(OptimizedCompiler.java:137)
    at nez.parser.OptimizedCompiler.encodePchoice(OptimizedCompiler.java:110)
...
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.PlainCompiler.encodePsequence(PlainCompiler.java:113)
    at nez.lang.expr.Psequence.encode(Psequence.java:175)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.PlainCompiler.encodePsequence(PlainCompiler.java:113)
    at nez.lang.expr.Psequence.encode(Psequence.java:175)
    at nez.parser.PlainCompiler.encode(PlainCompiler.java:46)
    at nez.parser.OptimizedCompiler.encodePredicatedChoice(OptimizedCompiler.java:137)
...

```

**Comment by imasahiro** [comment]
fixed by 7b3ffa3
